[package]
name = "snake"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
lalrpop-util = { version = "0.19.6", features = [ "lexer" ] }
regex = "1"

[dev-dependencies]
